"""Initial migration

Revision ID: 814688a6ce16
Revises: 
Create Date: 2023-07-13 19:18:28.215481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814688a6ce16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
