"""platforms

Revision ID: cfd764be3863
Revises: ff24f17b81f4
Create Date: 2023-08-02 22:25:04.407767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd764be3863'
down_revision = 'ff24f17b81f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
