"""IMG

Revision ID: ff24f17b81f4
Revises: 47ac834ed392
Create Date: 2023-08-02 22:16:21.328287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import JSON

# revision identifiers, used by Alembic.
revision = 'ff24f17b81f4'
down_revision = '47ac834ed392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('game') as batch_op:
        batch_op.alter_column('img', nullable=True)
        batch_op.alter_column('name', nullable=True)
        batch_op.alter_column('companies', type_=JSON(),unique=False, nullable=True)
        batch_op.alter_column('platforms', type_=JSON(),unique=False, nullable=True)
        batch_op.alter_column('date',unique=False, nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'date',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('game', 'platforms',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('game', 'companies',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('game', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('game', 'img',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
